export { AdvancedSection } from './AdvancedSection';
export { ClaudeCodeSection } from './ClaudeCodeSection';
export { ConnectionSection } from './ConnectionSection';
export { GeneralSection } from './GeneralSection';
export { KeyboardShortcutsSection } from './KeyboardShortcutsSection';
export { NotificationsSection } from './NotificationsSection';
export { PluginsSettings } from './PluginsSettings';
export { ThemeEditor } from './ThemeEditor';
export { WorkspaceSection } from './WorkspaceSection';
