import { JSX } from 'react';
import { formatBytes } from '@renderer/utils/formatters';

import { CategoryCleanupPanel, type CategoryColumn } from './CategoryCleanupPanel';

import type { Candidate } from '@shared/types';

const COLUMNS: CategoryColumn[] = [
  {
    key: 'name',
    label: 'Cache',
    render: (c: Candidate) => (
      <span className="text-foreground">
        {c.path.split('/').pop()}
        {c.meta?.sensitive === 'true' && (
          <span className="ml-2 rounded-sm bg-amber-500/15 px-1 py-px text-[9px] font-medium text-amber-500">
            may contain sensitive text
          </span>
        )}
      </span>
    ),
  },
  { key: 'bytes', label: 'Size', align: 'right', render: (c) => formatBytes(c.bytes) },
  { key: 'modTime', label: 'Last refreshed', render: (c) => c.modTime.toLocaleString() },
  { key: 'regeneratedBy', label: 'Regenerated by', render: (c) => c.meta?.regeneratedBy ?? '' },
];

// stats-cache.json has no raw-file-read binding (readPlanFile is scoped to
// plans/ only) — skipping the raw JSON viewer; see panel description below.
export const CachesCleanupPanel = (): JSX.Element => (
  <CategoryCleanupPanel
    title="Caches"
    description="Small regenerable caches the CLI rebuilds on its own schedule. Cleared immediately (plain delete, not moved to trash) — the right call for paste-cache entries, which may hold pasted secrets. stats-cache.json backs the analytics view's usage data; there is no in-app raw-JSON viewer for it."
    families={[{ id: 'caches', label: '' }]}
    columns={COLUMNS}
    deletePolicy="plain"
  />
);
